### ISSUE TITLE
Languages Aren’t Useful

### ISSUE THREAD

**Issue by SalladShooter** [LyubomirT/chainsaw-human-typing#12]
On the “ul” with the list of to e different language options, it isn’t friendly to those who read and speak the languages. Instead of the languages showing in the current language it should show the list in their languages like “French” - “ Français”, etc. it would help those who speak the language get out of one if they misclicked or wanted to see it in their language.

**Comment by LyubomirT** [comment]
Thank you for the issue @SalladShooter! I'll make sure to implement that as soon as possible.

**Comment by LyubomirT** [comment]
Fixed in `1.2.2`.
